- hosts: all
  user: vagrant
  sudo: yes

  tasks:

  - name: Update system (this may take a while...)
    apt: update_cache=yes
    
  - name: Install dependencies
    apt: name={{item}} state=latest update_cache=yes
    with_items:
        - wget
        - curl
        - git
        - docker.io

  - name: Create directory per project
    file: state=directory path=/home/vagrant/dockerfiles/"{{item}}"
    with_items:
        - Kettle
        - Openrefine
        - petl
        - pygrametl
        - csv-to-api
        - DataBeam
        - instant-api-py

  - name: Copy cleaning tools Dockerfiles
    copy: src=../limpieza/{{item}}/Dockerfile dest=/home/vagrant/dockerfiles/{{item}}/ mode=0777
    with_items:
        - Kettle
        - OpenRefine
        - petl
        - pygrametl
 
  - name: Copy data delivery tools Dockerfiles
    copy: src=../entrega-de-datos/{{item}}/Dockerfile dest=/home/vagrant/dockerfiles/{{item}}/ mode=0777
    with_items:
        - csv-to-api
        - DataBeam
        - instant-api-py
